#include<iostream>
#include<exception>

int main(){
	throw std::runtime_error("test_error");
	
}
